source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target ‘OZO’ do
    pod 'SnapKit', '~> 3.0.2'
    pod 'Alamofire', '~> 4.0'
    pod 'HandyJSON', '~> 1.3.0'
    pod 'Toast-Swift', '~> 2.0.0'
end
